name: On-Demand Build

on:
  workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: Linux
            artifacts: |
              assets/
              target/release/centripetal
          - os: windows-latest
            name: Windows
            artifacts: |
              assets/
              target/release/centripetal.exe
              target/release/build/mimalloc-redirect-**/out/bin/**.dll
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          token: ${{ secrets.CHECKOUT_TOKEN }}
      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ''
      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install g++ pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0 libwayland-dev libxkbcommon-dev
      - name: Compile Release build with `dev` feature
        run: |
          cargo clean --package mimalloc-redirect
          cargo build --release --no-default-features --features="dev"
      - name: Copy files to a common directory
        uses: nearform-actions/github-action-copy-files@v1
        with:
          source: ${{ matrix.artifacts }}
          destination: './out/'
          options: |
            {
              "overwrite": true,
              "flat": true
            }
      - name: Upload game as a GitHub Action artifact
        uses: actions/upload-artifact@v4
        with:
          name: Centripetal ${{ matrix.name }}
          path: './out/**'
          if-no-files-found: error
          compression-level: 9
          retention-days: 30
